name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.7
  http: ^0.13.3
  sqflite: ^2.0.0+4
  path: ^1.8.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/face.jpg
    - assets/talk.jpg
    - assets/line.jpg
    - assets/logo.png
    - assets/cloud.png
    - assets/maybay.png
    - assets/line.png
    - assets/sydney.png
    - assets/dragon-bridge.png
    - assets/halong.png
    - assets/guide1.png
    - assets/guide2.png
    - assets/guide3.png
    - assets/guide4.png
    - assets/profile.png
    - assets/picture1.png
    - assets/picture2.png
    - assets/picture3.png
    - assets/picture4.png
    - assets/picture5.png
    - assets/picture6.png
    - assets/picture7.png
    - assets/background.png
    - assets/Sapa.jpg
    - assets/hoian.jpg
    - assets/newyork.jpg
    - assets/paris.jpg